Repository elementor/hello-plus, pull requests merged in 2025-07, with the labels that each got.

#343 Internal: Allow widget editing on elementor domain [TMZ-739]
  modules/template-parts/assets/js/editor/module.js
  modules/template-parts/widgets/ehp-widget-base.php
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#344 Internal: Allow addign widgets on library [TMZ-739]
  modules/template-parts/documents/ehp-document-base.php
Labels: 1 min review

#345 Fix: Do not show common controls for Flex footer. Show container on library [TMZ-743] [TMZ-739]
  modules/template-parts/assets/js/editor/hooks/ui/select.js
  modules/template-parts/assets/js/editor/module.js
Labels: 1 min review

#348 Tweak: Allow filtering upsale data [TMZ-759]
  modules/template-parts/widgets/ehp-header.php
Labels: 1 min review

#350 Release: Version 1.7.0
  .github/workflows/build.yml
  includes/utils.php
  modules/template-parts/assets/js/editor/module.js
  modules/template-parts/widgets/ehp-header.php
  package-lock.json
  package.json
  readme.txt
Labels: 1 min review, missing-jira

#351 Internal: Allow users to override whether the plugin should behave as on the client or on the library [TMZ-742]
  includes/utils.php
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#352 Internal: Update controls specificity [TMZ-783]
  modules/content/classes/render/widget-contact-render.php
  modules/content/widgets/contact.php
  modules/content/widgets/cta.php
  modules/content/widgets/flex-hero.php
  modules/content/widgets/zig-zag.php
Labels: 1 min review

#353 Internal: Tweak kit filtering to always return an array [TMZ-789]
  modules/admin/classes/rest/onboarding-settings.php
  package-lock.json
  package.json
  readme.txt
Labels: 1 min review

#355 Release: Merge 1.7.1 into master
  hello-plus.php
  modules/admin/classes/rest/onboarding-settings.php
  package-lock.json
  package.json
  readme.txt
Labels: 1 min review, missing-jira

#358 Internal: Create cherry pick workflow
  .github/workflows/cherry-pick-pr.yml
  .github/workflows/cherry-pick-validation.yml
Labels: 1 min review, missing-jira, cp_1.7.1

#362 Internal: Handle empty cherry pick scenario [TMZ-769]
  .github/workflows/cherry-pick-pr.yml
Labels: 5 min review

#365 Fix: Show contact buttons style controls for connect [TMZ-714] [TMZ-807]
  modules/template-parts/widgets/ehp-header.php
Labels: 1 min review

#366 Tweak: Activate header and footer on import [TMZ-795]
  modules/template-parts/classes/runners/import.php
Labels: 5 min review

#357 Fix: Refactor script dependencies to work when user is logged out [TMZ-797]
  modules/forms/module.php
Labels: 1 min review

#374 Fix: Refactor script dependencies to work when user is logged out [TMZ-797] (#359)
  hello-plus.php
  modules/forms/module.php
  package-lock.json
  package.json
  readme.txt
Labels: cp_1.7

#383 Internal: Update cherry pick PR format for Jira compatibility [TMZ-822]
  .github/workflows/cherry-pick-pr.yml
Labels: 1 min review

#382 Fix: Refactor widget code and fix issues with dropdown [TMZ-811] [TMZ-812]
  classes/render-base.php
  classes/renderable.php
  classes/widget-utils.php
  modules/template-parts/assets/scss/hello-plus-header.scss
  modules/template-parts/classes/render/header/render-contact-buttons.php
  modules/template-parts/classes/render/header/render-ctas-container.php
  modules/template-parts/classes/render/header/render-menu-cart.php
  modules/template-parts/classes/render/header/render-navigation.php
  modules/template-parts/classes/render/widget-header-render.php
  modules/template-parts/widgets/ehp-header.php
Labels: 30 min review, cp_1.7

#386 Tweak: Ensure responsive menu works as expected [TMZ-810]
  modules/template-parts/assets/scss/hello-plus-header.scss
Labels: 1 min review, cp_1.7

#388 Internal: Remove the cherry pick PR title truncation [TMZ-822]
  .github/workflows/cherry-pick-pr.yml
Labels: 1 min review

#389 Fix: position of tab, visbility of hamburger menu, add to cart [TMZ-829] [TMZ-833] [TMZ-834]
  modules/template-parts/classes/render/widget-header-render.php
  modules/template-parts/module.php
  modules/template-parts/widgets/ehp-header.php
Labels: 1 min review, 🚨 2 Unresolved Thread(s), cp_1.7

#392 Fix: Remove interaction between forms lite and pro [TMZ-832]
  modules/forms/fields/acceptance.php
Labels: 1 min review, cp_1.7

#394 Tweak: Recalculate height when resizing [TMZ-830]
  modules/template-parts/assets/js/handlers/hello-plus-header-fe.js
Labels: 1 min review, 🚨 1 Unresolved Thread(s), cp_1.7

#396 Fix: Do not trigger elementor onboarding, header alignment [TMZ-837] [TMZ-835]
  modules/admin/classes/ajax/setup-wizard.php
  modules/template-parts/assets/scss/hello-plus-header.scss
Labels: 1 min review, 🚨 1 Unresolved Thread(s), cp_1.7

#399 Internal: Implement modular action approach [TMZ-804]
  .github/actions/build-plugin/action.yml
  .github/actions/deploy-to-wordpress-org/action.yml
  .github/actions/install-svn/action.yml
  .github/actions/prepare-plugin-env/action.yml
  .github/actions/validate-plugin-build/action.yml
  .github/workflows/one-click-release.yml
Labels: 5 min review

#402 Fix: Show products in editor, fix menu padding [TMZ-841] [TMZ-840]
  modules/admin/components/admin-controller.php
  modules/template-parts/assets/scss/hello-plus-header.scss
Labels: 1 min review, 🚨 2 Unresolved Thread(s), cp_1.7

#404 Internal: Ensure floting elements show with pro [TMZ-847]
  modules/template-parts/classes/runners/import-floating-elements.php
Labels: 1 min review, cp_1.7

#406 Release: Bump versions and changelog
  hello-plus.php
  package-lock.json
  package.json
  readme.txt
Labels: 1 min review, missing-jira, cp_1.7
