Repository elementor/hello-plus, pull requests merged in 2025-06, with the labels that each got.

#304 Fix: Header and e-floating-bars sticky prioritization [TMZ-194]
  modules/template-parts/assets/js/handlers/hello-plus-header-fe.js
  modules/template-parts/assets/scss/hello-plus-header.scss
Labels: 1 min review

#324 Fix: Prevent modal close when pressing esc [TMZ-446]
  modules/template-parts/assets/js/editor/module.js
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#329 Header: Menu cart logic [TMZ-558]
  includes/utils.php
  modules/template-parts/classes/render/widget-header-render.php
  modules/template-parts/widgets/ehp-header.php
Labels: 1 min review

#331 Header + Floating Bars: fix wobbly header when floating bars is not sticky [TMZ-706]
  modules/template-parts/assets/js/handlers/hello-plus-header-fe.js
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#325 Header: Menu cart [TMZ-558]
  modules/template-parts/assets/js/handlers/hello-plus-header-fe.js
  modules/template-parts/assets/scss/hello-plus-header.scss
  modules/template-parts/classes/render/widget-header-render.php
  modules/template-parts/widgets/ehp-header.php
Labels: 30 min review

#334 Fix: Refactor theme filter and add compatibility layer [TMZ-710]
  includes/utils.php
  modules/admin/classes/rest/onboarding-settings.php
  modules/template-parts/components/checklist.php
Labels: 1 min review, 🚨 1 Unresolved Thread(s)

#335 Release: Release version 1.7.0
  hello-plus.php
  modules/template-parts/assets/js/handlers/hello-plus-header-fe.js
  modules/template-parts/assets/scss/hello-plus-header.scss
  modules/template-parts/classes/render/widget-header-render.php
  modules/template-parts/widgets/ehp-header.php
  package-lock.json
  readme.txt
Labels: 🚨 2 Unresolved Thread(s), 30 min review, missing-jira

#338 Tweak: Change logo color and capitalization of steps in the Setup Wizard [TMZ-731]
  modules/admin/assets/images/elementor-notice-icon.svg
  modules/admin/assets/js/components/onboarding/navigation.js
  modules/admin/assets/js/components/top-bar/top-bar-content.js
  readme.txt
Labels: 1 min review
